FROM openjdk:11-latest

WORKDIR /app

# Копирование JAR-файла в контейнер
COPY producer/build/libs/producer-1.0-SNAPSHOT.jar producer.jar

# Команда для запуска JAR-файла
CMD ["java", "-jar", "producer.jar"]
