#Порт, на котором будет запущен встроенный томкат
server:
  port: 8090
  application:
    name: gran-docs
  ssl:
    enabled: false
    key-store: classpath:keystore.p12
    key-store-password: qwerty
    key-store-type: PKCS12
    key-password: qwerty
    client-auth: need
    trust-store:
      classpath: truststore.p12
    trust-store-password: qwerty
    trust-store-type: PKCS12

spring:
  resources:
  add-mappings: true

  #DB properties:
  #PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/gran-docs
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #определяет, регистрируется ли сервис как клиент на Eureka Server.
eureka:
  client:
    register-with-eureka: false
    #получать или нет информацию о зарегистрированных клиентах.
    fetch-registry: false

springdoc:
  api-docs:path: /api-docs

logging:
  level:
    ru:
      gransoft: DEBUG

hibernate:
  show_sql: true
  hbm2ddl:
    auto: update

